[project]
authors = ["pyramidheadshark <pyramidheadshark@gmail.com>"]
channels = ["conda-forge"]
name = "i-hate-my-life-and-quizlet"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
streamlit = ">=1.43.2, <2"
dotenv = ">=0.9.9, <0.10"
google-generativeai = ">=0.8.4, <0.9"
pandas = ">=2.2.3, <3"
